src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\JoinColumn;
use Doctrine\ORM\Mapping\ManyToOne;
use Doctrine\ORM\Mapping\OneToMany;
use Gedmo\Mapping\Annotation as Gedmo;
use Gedmo\Mapping\Annotation\Slug;
use Gedmo\Mapping\Annotation\Timestampable;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: ProductRepository::class)]
class Product
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $description = null;

    /**
     * @var \DateTime
     * @Timestampable(on="create")
     * @ORM\Column(type="datetime")
     * @Assert\DisableAutoMapping()
     */
    #[Timestampable(on: 'create')]
    #[ORM\Column(type: Types::DATETIME_IMMUTABLE)]
    private $created_at = null;

    #[ORM\Column(length: 100)]
    private ?string $creator_country = null;

    #[Slug(fields: ['name'])]
    #[ORM\Column(length: 255)]
    private ?string $slug = null;

    #[ORM\Column]
    private ?bool $is_active = null;

    #[ORM\OneToMany(mappedBy: 'product', targetEntity: ProductImage::class)]
    private Collection $productImages;

    #[ORM\ManyToOne(inversedBy: 'products')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Category $category = null;

    #[ORM\ManyToMany(targetEntity: Features::class, inversedBy: 'products')]
    private Collection $features;

    #[ORM\Column(nullable: true)]
    #[ORM\OrderBy(["sort_index" => "DESC"])]
    private ?int $sort_index = null;

    #[OneToMany(targetEntity: ProductSeller::class, mappedBy: 'product')]
    private $productSeller = [];

    #[ORM\OneToMany(mappedBy: 'product', targetEntity: Review::class)]
    private Collection $reviews;

    public function __construct()
    {
        $this->productImages = new ArrayCollection();
        $this->features = new ArrayCollection();
        $this->reviews = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getCreatorCountry(): ?string
    {
        return $this->creator_country;
    }

    public function setCreatorCountry(string $creator_country): self
    {
        $this->creator_country = $creator_country;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function isIsActive(): ?bool
    {
        return $this->is_active;
    }

    public function setIsActive(bool $is_active): self
    {
        $this->is_active = $is_active;

        return $this;
    }

    /**
     * @return Collection<int, ProductImage>
     */
    public function getProductImages(): Collection
    {
        return $this->productImages;
    }

    public function addProductImage(ProductImage $productImage): self
    {
        if (!$this->productImages->contains($productImage)) {
            $this->productImages->add($productImage);
            $productImage->setProduct($this);
        }

        return $this;
    }

    public function removeProductImage(ProductImage $productImage): self
    {
        if ($this->productImages->removeElement($productImage)) {
            // set the owning side to null (unless already changed)
            if ($productImage->getProduct() === $this) {
                $productImage->setProduct(null);
            }
        }

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    /**
     * @return Collection<int, Features>
     */
    public function getFeatures(): Collection
    {
        return $this->features;
    }

    public function addFeature(Features $feature): self
    {
        if (!$this->features->contains($feature)) {
            $this->features->add($feature);
        }

        return $this;
    }

    public function removeFeature(Features $feature): self
    {
        $this->features->removeElement($feature);

        return $this;
    }

    public function getSortIndex(): ?int
    {
        return $this->sort_index;
    }

    public function setSortIndex(?int $sort_index): self
    {
        $this->sort_index = $sort_index;

        return $this;
    }

    /**
     * @return Collection<int, Review>
     */
    public function getReviews(): Collection
    {
        return $this->reviews;
    }

    public function addReview(Review $review): self
    {
        if (!$this->reviews->contains($review)) {
            $this->reviews->add($review);
            $review->setProduct($this);
        }

        return $this;
    }

    public function removeReview(Review $review): self
    {
        if ($this->reviews->removeElement($review)) {
            // set the owning side to null (unless already changed)
            if ($review->getProduct() === $this) {
                $review->setProduct(null);
            }
        }

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $phone = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $full_name = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $avatar = null;

    #[ORM\Column(length: 255)]
    private ?string $email = null;

    #[ORM\OneToMany(mappedBy: 'User', targetEntity: ApiToken::class)]
    private Collection $apiTokens;

    public function __construct()
    {
        $this->apiTokens = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->phone;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->phone;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFullName(): ?string
    {
        return $this->full_name;
    }

    public function setFullName(?string $full_name): self
    {
        $this->full_name = $full_name;

        return $this;
    }

    public function getAvatar(): ?string
    {
        return $this->avatar;
    }

    public function setAvatar(?string $avatar): self
    {
        $this->avatar = $avatar;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getImagePath()
    {
        return 'assets/img/content/home/' . $this->getAvatar();
    }

    /**
     * @return Collection<int, ApiToken>
     */
    public function getApiTokens(): Collection
    {
        return $this->apiTokens;
    }

    public function addApiToken(ApiToken $apiToken): self
    {
        if (!$this->apiTokens->contains($apiToken)) {
            $this->apiTokens->add($apiToken);
            $apiToken->setUser($this);
        }

        return $this;
    }

    public function removeApiToken(ApiToken $apiToken): self
    {
        if ($this->apiTokens->removeElement($apiToken)) {
            // set the owning side to null (unless already changed)
            if ($apiToken->getUser() === $this) {
                $apiToken->setUser(null);
            }
        }

        return $this;
    }
}

templates/products/catalog.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <body class="Site">
    <!--if lt IE 8
    p.error-browser
        | Ваш браузер&nbsp;
        em устарел!&nbsp;
        a(href="http://browsehappy.com/") Выберите новую версию
            +s
            | браузера здесь&nbsp;
        | для правильного отображения сайта.
    -->

<div class="Middle Middle_top">
    <div class="Middle-top">
        <div class="wrap">
            <div class="Middle-header">
                <h1 class="Middle-title">Каталог</h1>
                <ul class="breadcrumbs Middle-breadcrumbs">
                    <li class="breadcrumbs-item"><a href="index.html">Главная</a></li>
                    <li class="breadcrumbs-item breadcrumbs-item_current"><span>Каталог</span></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="Section Section_column Section_columnLeft">
        <div class="wrap">
            <div class="Section-column">
                <div class="Section-columnSection">
                    <header class="Section-header">
                        <strong class="Section-title">Фильтр</strong>
                    </header>
                    <div class="Section-columnContent">
                        <form class="form" method="post">
                            <div class="form-group">
                                <div class="range Section-columnRange">
                                    <input class="range-line" id="price" name="price" type="text" data-type="double"
                                           data-min="7" data-max="50" data-from="7" data-to="27"/>
                                    <div class="range-price">Цена:&#32;
                                        <div class="rangePrice"></div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <input class="form-input form-input_full" id="title" name="title" type="text"
                                       placeholder="Название"/>
                            </div>
                            <div class="form-group">
                                <select class="form-select" name="seller">
                                    <option selected="selected" disabled="disabled">Продавец</option>
                                    {% for seller in sellers %}
                                    <option value="{{ seller.id }}">{{ seller.title }}</option>
                                    {%endfor %}
                                </select>
                            </div>
                            <div class="form-group">
                                <label class="toggle">
                                    <input type="checkbox"/><span class="toggle-box"></span><span
                                            class="toggle-text">Только с небитым экраном</span>
                                </label>
                            </div>
                            <div class="form-group">
                                <select class="form-select" name="features[]" id="features" multiple size="4">
                                    {% for feature in features %}
                                    <option value="{{ feature.id }}">{{ feature.value }}</option>
                                    {%endfor %}
                                </select>
                            </div>
                            <div class="form-group">

                                <div class="buttons">
                                    <button type="submit" class="btn btn_square btn_dark btn_narrow" >Применить</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="Section-content">
                <div class="Sort">
                    <div class="Sort-title">Сортировать по:
                    </div>
                    <div class="Sort-variants"><a class="Sort-sortBy Sort-sortBy_dec" href="{{ path('app_show_catalog', {sort: 'popul'})}}">Популярности</a><a
                                class="Sort-sortBy" href="{{ path('app_show_catalog', {sort: 'price'})}}">Цене</a><a class="Sort-sortBy" href="{{ path('app_show_catalog', {sort: 'otzv'})}}">Отзывам</a><a
                                class="Sort-sortBy Sort-sortBy_inc" href="{{ path('app_show_catalog', {sort: 'new'})}}">Новизне</a>
                    </div>
                </div>
                <div class="Cards">
                    {% for product in paginator %}
                        <div class="Card"><a class="Card-picture" href="{{ path('app_show_product', { slug: product.slug }) }}"><img
                                        src="{{ asset(images.0.getImagePath ) }}"
                                        alt="card.jpg"/></a>
                            <div class="Card-content">
                                <strong class="Card-title"><a
                                            href="{{ path('app_show_product', { slug: product.slug }) }}">{{ product.name }}</a>
                                </strong>
                                <div class="Card-description">
                                    <div class="Card-cost"><span
                                                class="Card-priceOld">${{ productSeller.aVGByProductSlug( product.slug ) | number_format(0) }}.00</span><span
                                                class="Card-price">${{ productSeller.aVGDiscountByProductSlug( product.slug ) | number_format(0) }}.00</span>
                                    </div>
                                    <div class="Card-category">{{ categoryProduct.findCategory( product.category.id ) }}
                                    </div>
                                    <div class="Card-hover"><a class="Card-btn" href="{{ path('app_show_product', { slug: product.slug }) }}"><img
                                                    src={{ asset('assets/img/icons/card/bookmark.svg')}} alt="bookmark.svg"/></a><a
                                                class="Card-btn" href="#"><img src="{{ asset('assets/img/icons/card/cart.svg') }}"
                                                                               alt="cart.svg"/></a><a class="Card-btn"
                                                                                                      href={{ path('app_show_compare') }}><img
                                                    src="{{ asset('assets/img/icons/card/change.svg') }}" alt="change.svg"/></a>
                                    </div>
                                </div>
                            </div>
                            <div class="Card-sale">-60%
                            </div>
                        </div>
                    {% endfor %}
                </div>
                <div class="Pagination">
                    <div class="Pagination-ins">
                        {{ knp_pagination_render(paginator) }}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/products/sale.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<body class="Site">
  <!--if lt IE 8
  p.error-browser
      | Ваш браузер&nbsp;
      em устарел!&nbsp;
      a(href="http://browsehappy.com/") Выберите новую версию
          +s
          | браузера здесь&nbsp;
      | для правильного отображения сайта.
  -->
  <div class="Middle Middle_top">
    <div class="Middle-top">
      <div class="wrap">
        <div class="Middle-header">
          <h1 class="Middle-title">Скидки</h1>
          <ul class="breadcrumbs Middle-breadcrumbs">
            <li class="breadcrumbs-item"><a href="index.html">Главная</a></li>
            <li class="breadcrumbs-item breadcrumbs-item_current"><span>Скидки</span></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="Section">
      <div class="wrap">
        <div class="Cards Cards_blog">
          <div class="Card"><a class="Card-picture" href="#"><img src="assets/img/content/sale/product.png" alt="product.png"/></a>
            <div class="Card-date">
              <strong class="Card-date-number">24
              </strong><span class="Card-date-month">nov</span>
            </div>
            <div class="Card-pin">
            </div>
            <div class="Card-content">
              <strong class="Card-title"><a href="#">Basic Time Management Advanced Course</a>
              </strong>
              <div class="Card-description">Lorem ipsum dolor sit amet consectetuer adipiscing elit sed diam nonummy nibh euismod tincid  unt ut laoreet dolore
              </div>
            </div>
          </div>
          <div class="Card"><a class="Card-picture" href="#"><img src="assets/img/content/sale/product.png" alt="product.png"/></a>
            <div class="Card-content">
              <strong class="Card-title"><a href="#">Music Playing Featured Technologies For Children</a>
              </strong>
              <div class="Card-description">Lorem ipsum dolor sit amet consectetuer adipiscing elit sed diam nonummy nibh euismod tincid  unt ut laoreet dolore
              </div>
            </div>
          </div>
          <div class="Card"><a class="Card-picture" href="#"><img src="assets/img/content/sale/product.png" alt="product.png"/></a>
            <div class="Card-date">
              <strong class="Card-date-number">26
              </strong><span class="Card-date-month">nov</span>
            </div>
            <div class="Card-content">
              <strong class="Card-title"><a href="#">Advanced Virtual Reality Tools Developers &amp; Gamers</a>
              </strong>
              <div class="Card-description">Lorem ipsum dolor sit amet consectetuer adipiscing elit sed diam nonummy nibh euismod tincid  unt ut laoreet dolore
              </div>
            </div>
          </div>
          <div class="Card"><a class="Card-picture" href="#"><img src="assets/img/content/sale/product.png" alt="product.png"/></a>
            <div class="Card-date">
              <strong class="Card-date-number">27
              </strong><span class="Card-date-month">nov</span>
            </div>
            <div class="Card-date Card-date_to">
              <strong class="Card-date-number">29
              </strong><span class="Card-date-month">nov</span>
            </div>
            <div class="Card-content">
              <strong class="Card-title"><a href="#">True Color 4K Monitors &amp; All in One Personal Books</a>
              </strong>
              <div class="Card-description">Lorem ipsum dolor sit amet consectetuer adipiscing elit sed diam nonummy nibh euismod tincid  unt ut laoreet dolore
              </div>
            </div>
          </div>
          <div class="Card"><a class="Card-picture" href="#"><img src="assets/img/content/sale/product.png" alt="product.png"/></a>
            <div class="Card-date">
              <strong class="Card-date-number">28
              </strong><span class="Card-date-month">nov</span>
            </div>
            <div class="Card-content">
              <strong class="Card-title"><a href="#">Advanced Virtual Reality Tools Developers &amp; Gamers</a>
              </strong>
              <div class="Card-description">Lorem ipsum dolor sit amet consectetuer adipiscing elit sed diam nonummy nibh euismod tincid  unt ut laoreet dolore
              </div>
            </div>
          </div>
          <div class="Card"><a class="Card-picture" href="#"></a>
            <div class="Card-date">
              <strong class="Card-date-number">29
              </strong><span class="Card-date-month">nov</span>
            </div>
            <div class="Card-date Card-date_to">
              <strong class="Card-date-number">29
              </strong><span class="Card-date-month">nov</span>
            </div>
            <div class="Card-content">
              <strong class="Card-title"><a href="#">Basic Time Management Advanced Course</a>
              </strong>
              <div class="Card-description">Lorem ipsum dolor sit amet consectetuer adipiscing elit sed diam nonummy nibh euismod tincid  unt ut laoreet dolore
              </div>
            </div>
          </div>
          <div class="Card"><a class="Card-picture" href="#"><img src="assets/img/content/sale/product.png" alt="product.png"/></a>
            <div class="Card-date">
              <strong class="Card-date-number">30
              </strong><span class="Card-date-month">nov</span>
            </div>
            <div class="Card-content">
              <strong class="Card-title"><a href="#">Music Playing Featured Technologies For Children</a>
              </strong>
              <div class="Card-description">Lorem ipsum dolor sit amet consectetuer adipiscing elit sed diam nonummy nibh euismod tincid  unt ut laoreet dolore
              </div>
            </div>
          </div>
          <div class="Card"><a class="Card-picture" href="#"><img src="assets/img/content/sale/product.png" alt="product.png"/></a>
            <div class="Card-date">
              <strong class="Card-date-number">31
              </strong><span class="Card-date-month">nov</span>
            </div>
            <div class="Card-content">
              <strong class="Card-title"><a href="#">Music Playing Featured Technologies For Children</a>
              </strong>
              <div class="Card-description">Lorem ipsum dolor sit amet consectetuer adipiscing elit sed diam nonummy nibh euismod tincid  unt ut laoreet dolore
              </div>
            </div>
          </div>
          <div class="Card"><a class="Card-picture" href="#"><img src="assets/img/content/sale/product.png" alt="product.png"/></a>
            <div class="Card-date">
              <strong class="Card-date-number">01
              </strong><span class="Card-date-month">dec</span>
            </div>
            <div class="Card-content">
              <strong class="Card-title"><a href="#">Basic Time Management Advanced Course</a>
              </strong>
              <div class="Card-description">Lorem ipsum dolor sit amet consectetuer adipiscing elit sed diam nonummy nibh euismod tincid  unt ut laoreet dolore
              </div>
            </div>
          </div>
          <div class="Card"><a class="Card-picture" href="#"><img src="assets/img/content/sale/product.png" alt="product.png"/></a>
            <div class="Card-date">
              <strong class="Card-date-number">02
              </strong><span class="Card-date-month">dec</span>
            </div>
            <div class="Card-content">
              <strong class="Card-title"><a href="#">Advanced Virtual Reality Tools Developers &amp; Gamers</a>
              </strong>
              <div class="Card-description">Lorem ipsum dolor sit amet consectetuer adipiscing elit sed diam nonummy nibh euismod tincid  unt ut laoreet dolore
              </div>
            </div>
          </div>
          <div class="Card"><a class="Card-picture" href="#"><img src="assets/img/content/sale/product.png" alt="product.png"/></a>
            <div class="Card-date">
              <strong class="Card-date-number">01
              </strong><span class="Card-date-month">dec</span>
            </div>
            <div class="Card-content">
              <strong class="Card-title"><a href="#">Basic Time Management Advanced Course</a>
              </strong>
              <div class="Card-description">Lorem ipsum dolor sit amet consectetuer adipiscing elit sed diam nonummy nibh euismod tincid  unt ut laoreet dolore
              </div>
            </div>
          </div>
          <div class="Card"><a class="Card-picture" href="#"><img src="assets/img/content/sale/product.png" alt="product.png"/></a>
            <div class="Card-date">
              <strong class="Card-date-number">02
              </strong><span class="Card-date-month">dec</span>
            </div>
            <div class="Card-content">
              <strong class="Card-title"><a href="#">Advanced Virtual Reality Tools Developers &amp; Gamers</a>
              </strong>
              <div class="Card-description">Lorem ipsum dolor sit amet consectetuer adipiscing elit sed diam nonummy nibh euismod tincid  unt ut laoreet dolore
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="Pagination">
    <div class="Pagination-ins"><a class="Pagination-element Pagination-element_prev" href="#"><img src="assets/img/icons/prevPagination.svg" alt="prevPagination.svg"/></a><a class="Pagination-element Pagination-element_current" href="#"><span class="Pagination-text">1</span></a><a class="Pagination-element" href="#"><span class="Pagination-text">2</span></a><a class="Pagination-element" href="#"><span class="Pagination-text">3</span></a><a class="Pagination-element Pagination-element_prev" href="#"><img src="assets/img/icons/nextPagination.svg" alt="nextPagination.svg"/></a>
    </div>
  </div>
{% endblock %}

templates/products/shop.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<body class="Site">
  <!--if lt IE 8
  p.error-browser
      | Ваш браузер&nbsp;
      em устарел!&nbsp;
      a(href="http://browsehappy.com/") Выберите новую версию
          +s
          | браузера здесь&nbsp;
      | для правильного отображения сайта.
  -->

  <div class="Middle Middle_top">
    <div class="Middle-top">
      <div class="wrap">
        <div class="Middle-header">
          <h1 class="Middle-title">Продавец {{ seller.title }}</h1>
          <ul class="breadcrumbs Middle-breadcrumbs">
            <li class="breadcrumbs-item"><a href="{{ path('app_shop_homepage') }}">Главная</a></li>
            <li class="breadcrumbs-item breadcrumbs-item_current"><span>О продавце</span></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="Section Section_column Section_columnLeft Section_columnWide">
      <div class="wrap">
        <div class="Section-column">
          <div class="Section-columnSection Section-columnSection_mark">
            <div class="media media_middle">
              <div class="media-image"><img src="{{ asset('assets/img/icons/contacts/phone.svg') }}" alt="phone.svg"/>
              </div>
              <div class="media-content">Тел:&#32;
                <nobr>{{ seller.phone }}</nobr>
              </div>
            </div>
          </div>
          <div class="Section-columnSection Section-columnSection_mark">
            <div class="media media_middle">
              <div class="media-image"><img src="{{ asset('assets/img/icons/contacts/address.svg') }}" alt="address.svg"/>
              </div>
              <div class="media-content">
                {{ seller.address }}
              </div>
            </div>
          </div>
          <div class="Section-columnSection Section-columnSection_mark">
            <div class="media media_middle">
              <div class="media-image"><img src="{{ asset('assets/img/icons/contacts/mail.svg') }}" alt="mail.svg"/></div>
              <div class="media-content">Email: {{ seller.email }}</div>
            </div>
          </div>
        </div>
        <div class="Section-content">
          <div class="row row_verticalCenter row_maxHalf">
            <div class="row-block">
              <div class="pict"><img src="{{ asset(seller.imagePath) }}" alt="bigGoods.png"/>
              </div>
            </div>
            <div class="row-block">
              <h2>{{ seller.title }}</h2>
              <p>{{ seller.description }}</p>
             <ul>
               {# <li>{{ seller.description }}
                </li>#}
              </ul>
            </div>
          </div>
          <header class="Section-header">
            <h2 class="Section-title">Популярные товары продавца</h2>
          </header>
          <div class="Cards">
            <div class="Card"><a class="Card-picture" href="#"><img src="assets/img/content/home/card.jpg" alt="card.jpg"/></a>
              <div class="Card-content">
                <strong class="Card-title"><a href="#">Corsair Carbide Series Arctic White Steel</a>
                </strong>
                <div class="Card-description">
                  <div class="Card-cost"><span class="Card-priceOld">$115.00</span><span class="Card-price">$85.00</span>
                  </div>
                  <div class="Card-category">Games / xbox
                  </div>
                  <div class="Card-hover"><a class="Card-btn" href="#"><img src="assets/img/icons/card/bookmark.svg" alt="bookmark.svg"/></a><a class="Card-btn" href="#"><img src="assets/img/icons/card/cart.svg" alt="cart.svg"/></a><a class="Card-btn" href="#"><img src="assets/img/icons/card/change.svg" alt="change.svg"/></a>
                  </div>
                </div>
              </div>
              <div class="Card-sale">-60%
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  {% endblock %}